@base_product_url = http://localhost:8080/product

POST {{base_product_url}}
Content-Type: application/json

{
  "name": "computer",
  "price": 1000
}
###
POST {{base_product_url}}
Content-Type: application/json

{
  "name": "drink",
  "price": 10
}
###
GET {{base_product_url}}
Accept: application/json
###
GET {{base_product_url}}/1
Accept: application/json
###
GET {{base_product_url}}/20
Accept: application/json
###
DELETE {{base_product_url}}/1
###
DELETE {{base_product_url}}/500
