@base_product_url = http://localhost:8080/api

POST {{base_product_url}}
Content-Type: application/json

{
  "name": "Budew"
}
###
POST {{base_product_url}}
Content-Type: application/json

{
  "name": "Charizard"
}
